name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest','macos-latest']
        ruby-version: [2.2.10]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Set up environment
      run: bundle install

    - name: Build
      run: bundle exec rake package
